<?php

declare(strict_types=1);

namespace App\Domains\WorkCore\System\Modules\Wizards\Services;

final class LayeredWizardQuestionCatalogue
{
    public static function defaults(): array
    {
        return [
            'schema_version' => '1.0.0',
            'definition' => [
                'key' => 'layered-company-launch',
                'version' => 1,
                'title' => 'Launch your business',
                'description' => 'A generic company launch wizard composed from governed question layers.',
                'category' => 'onboarding',
                'status' => 'published',
                'modes' => ['guided', 'conversation', 'hybrid'],
                'authority_model' => 'risk_based',
            ],
            'extension_slots' => [
                'business.optional' => ['section' => 'identity', 'order' => 900, 'sources' => ['tenant', 'ai']],
                'operations.optional' => ['section' => 'operations', 'order' => 900, 'sources' => ['tenant', 'ai']],
                'customer.optional' => ['section' => 'customer', 'order' => 900, 'sources' => ['tenant', 'ai']],
            ],
            'layers' => [
                'generic.company-launch' => [
                    'id' => 'generic.company-launch',
                    'kind' => 'generic',
                    'version' => '1.0.0',
                    'precedence' => 10,
                    'sections' => [
                        'identity' => [
                            'key' => 'identity',
                            'title' => 'Business identity',
                            'order' => 10,
                            'approval_mode' => 'section',
                            'questions' => [
                                'company.name' => [
                                    'key' => 'company.name',
                                    'question' => 'What name should customers and staff see for your business?',
                                    'response_type' => 'text',
                                    'required' => true,
                                    'risk' => 'medium',
                                    'handling' => 'ask',
                                    'target_owner' => 'Company',
                                    'order' => 10,
                                    'protected' => true,
                                    'mandatory_domain' => 'identity',
                                ],
                                'company.country_code' => [
                                    'key' => 'company.country_code',
                                    'question' => 'Which country is the business primarily operating in?',
                                    'response_type' => 'country',
                                    'required' => true,
                                    'risk' => 'medium',
                                    'handling' => 'infer_then_confirm',
                                    'target_owner' => 'Company',
                                    'order' => 20,
                                ],
                                'company.business_email' => [
                                    'key' => 'company.business_email',
                                    'question' => 'Which email should be used for business correspondence?',
                                    'response_type' => 'email',
                                    'required' => true,
                                    'risk' => 'medium',
                                    'handling' => 'ask',
                                    'target_owner' => 'Company settings',
                                    'order' => 30,
                                ],
                                'business.online_booking' => [
                                    'key' => 'business.online_booking',
                                    'question' => 'Should customers be able to book online?',
                                    'response_type' => 'boolean',
                                    'required' => false,
                                    'risk' => 'low',
                                    'handling' => 'ask_if_relevant',
                                    'target_owner' => 'Booking',
                                    'order' => 60,
                                ],
                            ],
                        ],
                        'privacy' => [
                            'key' => 'privacy',
                            'title' => 'Privacy',
                            'order' => 20,
                            'approval_mode' => 'section',
                            'questions' => [
                                'privacy.acceptance' => [
                                    'key' => 'privacy.acceptance',
                                    'question' => 'Do you accept the privacy and data-handling requirements for this workspace?',
                                    'response_type' => 'boolean',
                                    'required' => true,
                                    'risk' => 'high',
                                    'handling' => 'ask',
                                    'target_owner' => 'Governance',
                                    'order' => 10,
                                    'protected' => true,
                                    'mandatory_domain' => 'privacy',
                                ],
                            ],
                        ],
                        'operations' => [
                            'key' => 'operations',
                            'title' => 'Operations',
                            'order' => 30,
                            'approval_mode' => 'section',
                            'questions' => [
                                'business.service_model' => [
                                    'key' => 'business.service_model',
                                    'question' => 'How does the business deliver its products or services?',
                                    'response_type' => 'multi_select',
                                    'required' => true,
                                    'risk' => 'medium',
                                    'handling' => 'ask',
                                    'target_owner' => 'Operations',
                                    'order' => 10,
                                    'options' => ['onsite', 'field', 'remote', 'retail', 'delivery'],
                                ],
                            ],
                        ],
                        'customer' => [
                            'key' => 'customer',
                            'title' => 'Customer experience',
                            'order' => 40,
                            'approval_mode' => 'section',
                            'questions' => [],
                        ],
                        'payments' => [
                            'key' => 'payments',
                            'title' => 'Payments',
                            'order' => 50,
                            'approval_mode' => 'section',
                            'questions' => [
                                'payments.primary_method' => [
                                    'key' => 'payments.primary_method',
                                    'question' => 'Which payment method should be offered first?',
                                    'response_type' => 'select',
                                    'required' => true,
                                    'risk' => 'high',
                                    'handling' => 'ask',
                                    'target_owner' => 'Finance',
                                    'order' => 10,
                                    'options' => ['cash', 'payid', 'bank_transfer', 'card'],
                                    'protected' => true,
                                    'mandatory_domain' => 'payment',
                                ],
                            ],
                        ],
                        'security' => [
                            'key' => 'security',
                            'title' => 'Permissions',
                            'order' => 60,
                            'approval_mode' => 'section',
                            'questions' => [
                                'security.primary_admin' => [
                                    'key' => 'security.primary_admin',
                                    'question' => 'Who is the primary administrator responsible for permissions?',
                                    'response_type' => 'user_reference',
                                    'required' => true,
                                    'risk' => 'high',
                                    'handling' => 'ask',
                                    'target_owner' => 'Identity and access',
                                    'order' => 10,
                                    'protected' => true,
                                    'mandatory_domain' => 'permission',
                                ],
                            ],
                        ],
                        'compliance' => [
                            'key' => 'compliance',
                            'title' => 'Compliance',
                            'order' => 70,
                            'approval_mode' => 'section',
                            'questions' => [
                                'compliance.applicable' => [
                                    'key' => 'compliance.applicable',
                                    'question' => 'Which legal, industry or certification obligations apply?',
                                    'response_type' => 'multi_select',
                                    'required' => true,
                                    'risk' => 'high',
                                    'handling' => 'ask',
                                    'target_owner' => 'Compliance',
                                    'order' => 10,
                                    'options' => ['none_known', 'licensing', 'privacy', 'safety', 'industry_standard'],
                                    'protected' => true,
                                    'mandatory_domain' => 'compliance',
                                ],
                            ],
                        ],
                        'activation' => [
                            'key' => 'activation',
                            'title' => 'Evidence and activation',
                            'order' => 80,
                            'approval_mode' => 'section',
                            'questions' => [
                                'activation.evidence_ack' => [
                                    'key' => 'activation.evidence_ack',
                                    'question' => 'Do you confirm that required evidence will be supplied before governed features are activated?',
                                    'response_type' => 'boolean',
                                    'required' => true,
                                    'risk' => 'high',
                                    'handling' => 'ask',
                                    'target_owner' => 'Assurance',
                                    'order' => 10,
                                    'protected' => true,
                                    'mandatory_domain' => 'evidence',
                                ],
                                'activation.confirm' => [
                                    'key' => 'activation.confirm',
                                    'question' => 'Do you approve this launch configuration for activation review?',
                                    'response_type' => 'boolean',
                                    'required' => true,
                                    'risk' => 'high',
                                    'handling' => 'ask',
                                    'target_owner' => 'Activation',
                                    'order' => 20,
                                    'protected' => true,
                                    'mandatory_domain' => 'activation',
                                ],
                            ],
                        ],
                    ],
                ],
                'country.au' => [
                    'id' => 'country.au',
                    'kind' => 'country',
                    'version' => '1.0.0',
                    'precedence' => 20,
                    'sections' => [
                        'identity' => [
                            'key' => 'identity',
                            'title' => 'Business identity',
                            'order' => 10,
                            'questions' => [
                                'company.abn' => [
                                    'key' => 'company.abn',
                                    'question' => 'What is the business ABN?',
                                    'response_type' => 'text',
                                    'required' => true,
                                    'risk' => 'medium',
                                    'handling' => 'ask',
                                    'target_owner' => 'Company',
                                    'order' => 40,
                                ],
                                'company.gst_registered' => [
                                    'key' => 'company.gst_registered',
                                    'question' => 'Is the business registered for GST?',
                                    'response_type' => 'boolean',
                                    'required' => true,
                                    'risk' => 'medium',
                                    'handling' => 'ask',
                                    'target_owner' => 'Finance',
                                    'order' => 50,
                                ],
                            ],
                        ],
                    ],
                ],
                'vertical.field-home-services' => [
                    'id' => 'vertical.field-home-services',
                    'kind' => 'vertical_family',
                    'version' => '1.0.0',
                    'precedence' => 30,
                    'sections' => [
                        'operations' => [
                            'key' => 'operations',
                            'title' => 'Field and home service operations',
                            'order' => 30,
                            'questions' => [
                                'service.delivery_locations' => [
                                    'key' => 'service.delivery_locations',
                                    'question' => 'Where can field work be delivered?',
                                    'response_type' => 'multi_select',
                                    'required' => true,
                                    'risk' => 'medium',
                                    'handling' => 'ask',
                                    'target_owner' => 'Territories',
                                    'order' => 20,
                                    'options' => ['customer_premises', 'company_site', 'mobile', 'remote'],
                                ],
                            ],
                        ],
                    ],
                ],
                'subtype.cleaning' => [
                    'id' => 'subtype.cleaning',
                    'kind' => 'subtype',
                    'version' => '1.0.0',
                    'precedence' => 40,
                    'sections' => [
                        'operations' => [
                            'key' => 'operations',
                            'title' => 'Cleaning operations',
                            'order' => 30,
                            'questions' => [
                                'cleaning.service_types' => [
                                    'key' => 'cleaning.service_types',
                                    'question' => 'Which cleaning services do you provide?',
                                    'response_type' => 'multi_select',
                                    'required' => true,
                                    'risk' => 'medium',
                                    'handling' => 'ask',
                                    'target_owner' => 'Service catalogue',
                                    'order' => 30,
                                    'options' => ['residential', 'office', 'short_stay', 'commercial', 'medical'],
                                ],
                                'cleaning.turnover_window' => [
                                    'key' => 'cleaning.turnover_window',
                                    'question' => 'How much time is normally available between short-stay guests?',
                                    'response_type' => 'duration',
                                    'required' => false,
                                    'risk' => 'low',
                                    'handling' => 'ask_if_relevant',
                                    'target_owner' => 'Scheduling',
                                    'order' => 40,
                                    'when' => [
                                        'field' => 'cleaning.service_types',
                                        'operator' => 'includes',
                                        'value' => 'short_stay',
                                    ],
                                ],
                                'cleaning.equipment_supplied' => [
                                    'key' => 'cleaning.equipment_supplied',
                                    'question' => 'Who normally supplies equipment and consumables?',
                                    'response_type' => 'select',
                                    'required' => true,
                                    'risk' => 'medium',
                                    'handling' => 'ask',
                                    'target_owner' => 'Operations',
                                    'order' => 50,
                                    'options' => ['business', 'customer', 'mixed'],
                                ],
                            ],
                        ],
                    ],
                ],
                'capability.customer-portal' => [
                    'id' => 'capability.customer-portal',
                    'kind' => 'capability',
                    'version' => '1.0.0',
                    'precedence' => 50,
                    'sections' => [
                        'customer' => [
                            'key' => 'customer',
                            'title' => 'Customer experience',
                            'order' => 40,
                            'questions' => [
                                'customer.portal_access' => [
                                    'key' => 'customer.portal_access',
                                    'question' => 'What should customers be able to see in their portal?',
                                    'response_type' => 'multi_select',
                                    'required' => false,
                                    'risk' => 'medium',
                                    'handling' => 'ask_if_relevant',
                                    'target_owner' => 'Customer portal',
                                    'order' => 10,
                                    'options' => ['bookings', 'jobs', 'quotes', 'invoices', 'documents'],
                                ],
                            ],
                        ],
                    ],
                ],
                'capability.online-booking' => [
                    'id' => 'capability.online-booking',
                    'kind' => 'capability',
                    'version' => '1.0.0',
                    'precedence' => 50,
                    'sections' => [
                        'operations' => [
                            'key' => 'operations',
                            'title' => 'Operations',
                            'order' => 30,
                            'questions' => [
                                'booking.minimum_notice' => [
                                    'key' => 'booking.minimum_notice',
                                    'question' => 'What minimum notice is required for an online booking?',
                                    'response_type' => 'duration',
                                    'required' => false,
                                    'risk' => 'medium',
                                    'handling' => 'ask_if_relevant',
                                    'target_owner' => 'Booking',
                                    'order' => 80,
                                    'priority_when' => [
                                        'condition' => [
                                            'field' => 'business.online_booking',
                                            'operator' => 'truthy',
                                        ],
                                        'boost' => 200,
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
                'fallback.generic-service' => [
                    'id' => 'fallback.generic-service',
                    'kind' => 'fallback',
                    'version' => '1.0.0',
                    'precedence' => 40,
                    'sections' => [
                        'operations' => [
                            'key' => 'operations',
                            'title' => 'Products and services',
                            'order' => 30,
                            'questions' => [
                                'service.offering' => [
                                    'key' => 'service.offering',
                                    'question' => 'Describe the main products or services the business provides.',
                                    'response_type' => 'textarea',
                                    'required' => true,
                                    'risk' => 'medium',
                                    'handling' => 'ask',
                                    'target_owner' => 'Catalogue',
                                    'order' => 30,
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
}
