<?php

return [
    'default_expiry_days' => (int) env('TITAN_REACH_ASSISTED_LISTING_EXPIRY_DAYS', 30),
    'max_images' => (int) env('TITAN_REACH_ASSISTED_LISTING_MAX_IMAGES', 20),
    'destinations' => [
        'facebook-marketplace' => [
            'label' => 'Facebook Marketplace',
            'mode' => 'assisted',
            'adapter_available' => true,
            'platform' => null,
            'official_posting_url' => 'https://www.facebook.com/marketplace/create/item',
            'allowed_external_hosts' => ['facebook.com', 'www.facebook.com', 'm.facebook.com'],
            'content_types' => [
                'marketplace_listing',
                'classified_listing',
                'product_offer',
                'service_promotion',
                'property_listing',
                'vehicle_listing',
            ],
            'required_fields' => [
                'title',
                'description',
                'category',
                'condition',
                'price_minor',
                'currency',
                'location',
                'image_urls',
            ],
            'media_rules' => [
                'images' => true,
                'ordered_images' => true,
                'videos' => false,
            ],
            'capabilities' => [
                'prepare_package' => true,
                'copy_export' => true,
                'open_official_destination' => true,
                'manual_confirmation' => true,
                'renewal_tracking' => true,
                'enquiry_handoff' => true,
                'publish' => false,
                'schedule' => false,
                'edit' => false,
                'delete' => false,
                'analytics' => false,
                'inbox' => false,
                'pricing' => true,
                'inventory' => false,
            ],
            'approval_required' => true,
        ],
        'gumtree' => [
            'label' => 'Gumtree Australia',
            'mode' => 'assisted',
            'adapter_available' => true,
            'platform' => null,
            'official_posting_url' => 'https://www.gumtree.com.au/p-post-ad.html',
            'allowed_external_hosts' => ['gumtree.com.au', 'www.gumtree.com.au'],
            'content_types' => [
                'marketplace_listing',
                'classified_listing',
                'product_offer',
                'service_promotion',
                'property_listing',
                'vehicle_listing',
                'job_listing',
            ],
            'required_fields' => [
                'title',
                'description',
                'category',
                'condition',
                'price_minor',
                'currency',
                'location',
                'image_urls',
            ],
            'media_rules' => [
                'images' => true,
                'ordered_images' => true,
                'videos' => false,
            ],
            'capabilities' => [
                'prepare_package' => true,
                'copy_export' => true,
                'open_official_destination' => true,
                'manual_confirmation' => true,
                'renewal_tracking' => true,
                'enquiry_handoff' => true,
                'publish' => false,
                'schedule' => false,
                'edit' => false,
                'delete' => false,
                'analytics' => false,
                'inbox' => false,
                'pricing' => true,
                'inventory' => false,
            ],
            'approval_required' => true,
        ],
    ],
];
