<?php

return [
    'content_types' => [
        'social_post',
        'marketplace_listing',
        'classified_listing',
        'product_offer',
        'service_promotion',
        'business_update',
        'paid_creative',
        'event',
        'property_listing',
        'vehicle_listing',
        'job_listing',
    ],

    'destinations' => [
        'facebook' => [
            'mode'              => 'direct',
            'adapter_available' => true,
            'platform'          => 'facebook',
            'content_types'     => ['social_post', 'business_update', 'event', 'product_offer'],
            'required_fields'   => ['content'],
            'media_rules'       => ['images' => true, 'videos' => true],
            'capabilities'      => ['publish' => true, 'schedule' => true, 'edit' => false, 'delete' => false, 'analytics' => true, 'inbox' => false, 'pricing' => false, 'inventory' => false],
            'approval_required' => false,
        ],
        'instagram' => [
            'mode'              => 'direct',
            'adapter_available' => true,
            'platform'          => 'instagram',
            'content_types'     => ['social_post', 'product_offer', 'service_promotion'],
            'required_fields'   => ['content', 'media'],
            'media_rules'       => ['images' => true, 'videos' => true],
            'capabilities'      => ['publish' => true, 'schedule' => true, 'edit' => false, 'delete' => false, 'analytics' => true, 'inbox' => false, 'pricing' => false, 'inventory' => false],
            'approval_required' => false,
        ],
        'x' => [
            'mode'              => 'direct',
            'adapter_available' => true,
            'platform'          => 'x',
            'content_types'     => ['social_post', 'business_update'],
            'required_fields'   => ['content'],
            'media_rules'       => ['images' => true, 'videos' => false],
            'capabilities'      => ['publish' => true, 'schedule' => true, 'edit' => false, 'delete' => false, 'analytics' => true, 'inbox' => false, 'pricing' => false, 'inventory' => false],
            'approval_required' => false,
        ],
        'linkedin' => [
            'mode'              => 'direct',
            'adapter_available' => true,
            'platform'          => 'linkedin',
            'content_types'     => ['social_post', 'business_update', 'job_listing'],
            'required_fields'   => ['content'],
            'media_rules'       => ['images' => true, 'videos' => false],
            'capabilities'      => ['publish' => true, 'schedule' => true, 'edit' => false, 'delete' => false, 'analytics' => false, 'inbox' => false, 'pricing' => false, 'inventory' => false],
            'approval_required' => false,
        ],
        'tiktok' => [
            'mode'              => 'direct',
            'adapter_available' => true,
            'platform'          => 'tiktok',
            'content_types'     => ['social_post', 'product_offer', 'service_promotion'],
            'required_fields'   => ['content', 'media'],
            'media_rules'       => ['images' => true, 'videos' => true],
            'capabilities'      => ['publish' => true, 'schedule' => true, 'edit' => false, 'delete' => false, 'analytics' => false, 'inbox' => false, 'pricing' => false, 'inventory' => false],
            'approval_required' => false,
        ],
        'youtube' => [
            'mode'              => 'direct',
            'adapter_available' => true,
            'platform'          => 'youtube',
            'content_types'     => ['social_post', 'business_update'],
            'required_fields'   => ['content', 'video'],
            'media_rules'       => ['images' => false, 'videos' => true],
            'capabilities'      => ['publish' => true, 'schedule' => true, 'edit' => false, 'delete' => false, 'analytics' => false, 'inbox' => false, 'pricing' => false, 'inventory' => false],
            'approval_required' => false,
        ],
        'youtube-shorts' => [
            'mode'              => 'direct',
            'adapter_available' => true,
            'platform'          => 'youtube-shorts',
            'content_types'     => ['social_post'],
            'required_fields'   => ['content', 'video'],
            'media_rules'       => ['images' => false, 'videos' => true, 'orientation' => '9:16'],
            'capabilities'      => ['publish' => true, 'schedule' => true, 'edit' => false, 'delete' => false, 'analytics' => false, 'inbox' => false, 'pricing' => false, 'inventory' => false],
            'approval_required' => false,
        ],
        'ebay' => [
            'mode'              => 'partner',
            'adapter_available' => false,
            'platform'          => null,
            'content_types'     => ['marketplace_listing', 'product_offer', 'vehicle_listing'],
            'required_fields'   => ['title', 'description', 'price', 'images'],
            'media_rules'       => ['images' => true, 'videos' => false],
            'capabilities'      => ['publish' => false, 'schedule' => false, 'edit' => false, 'delete' => false, 'analytics' => false, 'inbox' => false, 'pricing' => true, 'inventory' => true],
            'approval_required' => true,
        ],
        'meta-ads' => [
            'mode'              => 'partner',
            'adapter_available' => false,
            'platform'          => null,
            'content_types'     => ['paid_creative', 'product_offer', 'service_promotion'],
            'required_fields'   => ['creative', 'objective', 'budget', 'schedule'],
            'media_rules'       => ['images' => true, 'videos' => true],
            'capabilities'      => ['publish' => false, 'schedule' => false, 'edit' => false, 'delete' => false, 'analytics' => false, 'inbox' => false, 'pricing' => true, 'inventory' => false],
            'approval_required' => true,
        ],
        'facebook-marketplace' => [
            'mode'              => 'assisted',
            'adapter_available' => true,
            'platform'          => null,
            'content_types'     => ['marketplace_listing', 'classified_listing', 'product_offer', 'property_listing', 'vehicle_listing'],
            'required_fields'   => ['title', 'description', 'price', 'images', 'location'],
            'media_rules'       => ['images' => true, 'videos' => false],
            'capabilities'      => ['publish' => false, 'schedule' => false, 'edit' => false, 'delete' => false, 'analytics' => false, 'inbox' => false, 'pricing' => true, 'inventory' => false, 'prepare_package' => true, 'open_destination' => true, 'manual_confirmation' => true],
            'approval_required' => true,
        ],
        'gumtree' => [
            'mode'              => 'assisted',
            'adapter_available' => true,
            'platform'          => null,
            'content_types'     => ['marketplace_listing', 'classified_listing', 'service_promotion', 'property_listing', 'vehicle_listing', 'job_listing'],
            'required_fields'   => ['title', 'description', 'price', 'images', 'location'],
            'media_rules'       => ['images' => true, 'videos' => false],
            'capabilities'      => ['publish' => false, 'schedule' => false, 'edit' => false, 'delete' => false, 'analytics' => false, 'inbox' => false, 'pricing' => true, 'inventory' => false, 'prepare_package' => true, 'open_destination' => true, 'manual_confirmation' => true],
            'approval_required' => true,
        ],
        'google-business-profile' => [
            'mode'              => 'partner',
            'adapter_available' => false,
            'platform'          => null,
            'content_types'     => ['business_update', 'event', 'product_offer', 'service_promotion'],
            'required_fields'   => ['content'],
            'media_rules'       => ['images' => true, 'videos' => false],
            'capabilities'      => ['publish' => false, 'schedule' => false, 'edit' => false, 'delete' => false, 'analytics' => false, 'inbox' => false, 'pricing' => false, 'inventory' => false],
            'approval_required' => false,
        ],
        'pinterest' => [
            'mode'              => 'partner',
            'adapter_available' => false,
            'platform'          => null,
            'content_types'     => ['social_post', 'product_offer', 'service_promotion', 'property_listing'],
            'required_fields'   => ['title', 'media', 'destination_url'],
            'media_rules'       => ['images' => true, 'videos' => true],
            'capabilities'      => ['publish' => false, 'schedule' => false, 'edit' => false, 'delete' => false, 'analytics' => false, 'inbox' => false, 'pricing' => false, 'inventory' => false],
            'approval_required' => false,
        ],
        'export' => [
            'mode'              => 'export_only',
            'adapter_available' => true,
            'platform'          => null,
            'content_types'     => ['social_post', 'marketplace_listing', 'classified_listing', 'product_offer', 'service_promotion', 'business_update', 'paid_creative', 'event', 'property_listing', 'vehicle_listing', 'job_listing'],
            'required_fields'   => [],
            'media_rules'       => ['images' => true, 'videos' => true],
            'capabilities'      => ['publish' => false, 'schedule' => false, 'edit' => false, 'delete' => false, 'analytics' => false, 'inbox' => false, 'pricing' => true, 'inventory' => true, 'prepare_package' => true, 'open_destination' => false, 'manual_confirmation' => true],
            'approval_required' => false,
        ],
    ],
];
