<?php

return [
    'environment' => env('EBAY_ENVIRONMENT', 'sandbox'),
    'client_id' => env('EBAY_CLIENT_ID'),
    'client_secret' => env('EBAY_CLIENT_SECRET'),
    'redirect_uri' => env('EBAY_REDIRECT_URI'),
    'marketplace_id' => env('EBAY_MARKETPLACE_ID', 'EBAY_AU'),
    'content_language' => env('EBAY_CONTENT_LANGUAGE', 'en-AU'),
    'scopes' => [
        'https://api.ebay.com/oauth/api_scope/sell.inventory',
        'https://api.ebay.com/oauth/api_scope/sell.account.readonly',
    ],
    'destination' => [
        'mode'              => 'direct',
        'adapter_available' => true,
        'platform'          => 'ebay',
        'content_types'     => ['marketplace_listing', 'product_offer', 'vehicle_listing'],
        'required_fields'   => [
            'sku',
            'marketplace_id',
            'merchant_location_key',
            'category_id',
            'condition',
            'quantity',
            'price',
            'title',
            'description',
            'image_urls',
            'fulfillment_policy_id',
            'payment_policy_id',
            'return_policy_id',
        ],
        'media_rules' => [
            'images' => true,
            'videos' => false,
            'ordered_images' => true,
        ],
        'capabilities' => [
            'publish' => true,
            'schedule' => false,
            'edit' => true,
            'delete' => false,
            'end_listing' => true,
            'analytics' => false,
            'inbox' => false,
            'pricing' => true,
            'inventory' => true,
            'status_reconciliation' => true,
            'buyer_question_handoff' => true,
        ],
        'approval_required' => true,
    ],
];
