<?php

return [
    'client_id' => env('GOOGLE_BUSINESS_PROFILE_CLIENT_ID'),
    'client_secret' => env('GOOGLE_BUSINESS_PROFILE_CLIENT_SECRET'),
    'redirect_uri' => env('GOOGLE_BUSINESS_PROFILE_REDIRECT_URI'),
    'authorization_url' => 'https://accounts.google.com/o/oauth2/v2/auth',
    'token_url' => 'https://oauth2.googleapis.com/token',
    'account_api_root' => 'https://mybusinessaccountmanagement.googleapis.com/v1',
    'business_information_api_root' => 'https://mybusinessbusinessinformation.googleapis.com/v1',
    'my_business_api_root' => 'https://mybusiness.googleapis.com/v4',
    'performance_api_root' => 'https://businessprofileperformance.googleapis.com/v1',
    'scopes' => [
        'https://www.googleapis.com/auth/business.manage',
    ],
    'timeout_seconds' => 20,
    'max_read_attempts' => 2,
    'destination' => [
        'mode'              => 'direct',
        'adapter_available' => true,
        'platform'          => 'google-business-profile',
        'content_types'     => [
            'business_update',
            'event',
            'product_offer',
            'service_promotion',
            'room_stay_offer',
            'membership_offer',
            'class_session_offer',
            'booking_offer',
        ],
        'required_fields' => ['content', 'location'],
        'media_rules' => [
            'images' => true,
            'videos' => false,
            'ordered_images' => true,
        ],
        'capabilities' => [
            'publish' => true,
            'schedule' => false,
            'edit' => false,
            'delete' => false,
            'analytics' => true,
            'inbox' => false,
            'pricing' => false,
            'inventory' => false,
            'photos' => true,
            'reviews' => true,
            'review_reply' => true,
            'account_discovery' => true,
            'location_discovery' => true,
            'status_reconciliation' => true,
        ],
        'approval_required' => true,
    ],
];
