<?php

return [
    'default_status' => 'PAUSED',
    'max_budget_minor' => (int) env('TITAN_REACH_META_ADS_MAX_BUDGET_MINOR', 10000000),
    'max_duration_days' => (int) env('TITAN_REACH_META_ADS_MAX_DURATION_DAYS', 365),
    'approval_permission' => 'titan-reach.paid_media.approve',
    'activation_permission' => 'titan-reach.paid_media.activate',
    'objectives' => [
        'OUTCOME_AWARENESS',
        'OUTCOME_TRAFFIC',
        'OUTCOME_ENGAGEMENT',
        'OUTCOME_LEADS',
        'OUTCOME_APP_PROMOTION',
        'OUTCOME_SALES',
    ],
    'preview_formats' => [
        'DESKTOP_FEED_STANDARD',
        'MOBILE_FEED_STANDARD',
        'INSTAGRAM_STANDARD',
        'INSTAGRAM_REELS',
        'FACEBOOK_REELS',
    ],
    'insight_fields' => [
        'campaign_name',
        'adset_name',
        'ad_name',
        'impressions',
        'reach',
        'clicks',
        'spend',
        'actions',
        'cost_per_action_type',
        'date_start',
        'date_stop',
    ],
    'destination' => [
        'mode'              => 'direct',
        'adapter_available' => true,
        'platform'          => 'facebook',
        'content_types'     => ['paid_creative', 'product_offer', 'service_promotion'],
        'required_fields'   => ['creative', 'objective', 'budget', 'schedule', 'ad_account_id'],
        'media_rules'       => ['images' => true, 'videos' => true],
        'capabilities'      => [
            'draft' => true,
            'recommendations' => true,
            'preview' => true,
            'sync_paused' => true,
            'activate' => true,
            'pause' => true,
            'insights' => true,
            'publish' => false,
            'schedule' => true,
            'edit' => true,
            'delete' => false,
            'analytics' => true,
            'inbox' => false,
            'pricing' => true,
            'inventory' => false,
        ],
        'approval_required' => true,
    ],
];
