<?php

return [
    'client_id' => env('PINTEREST_CLIENT_ID'),
    'client_secret' => env('PINTEREST_CLIENT_SECRET'),
    'redirect_uri' => env('PINTEREST_REDIRECT_URI'),
    'authorization_url' => 'https://www.pinterest.com/oauth/',
    'token_url' => 'https://api.pinterest.com/v5/oauth/token',
    'api_root' => 'https://api.pinterest.com/v5',
    'continuous_refresh' => true,
    'scopes' => [
        'boards:read',
        'pins:read',
        'pins:write',
        'user_accounts:read',
    ],
    'timeout_seconds' => 20,
    'max_read_attempts' => 2,
    'destination' => [
        'mode'              => 'direct',
        'adapter_available' => true,
        'platform'          => 'pinterest',
        'content_types'     => [
            'social_post',
            'product_offer',
            'service_promotion',
            'property_listing',
            'vehicle_listing',
            'room_stay_offer',
            'membership_offer',
            'class_session_offer',
            'booking_offer',
            'hire_rental_listing',
        ],
        'required_fields' => ['title', 'board_id', 'images'],
        'media_rules' => [
            'images' => true,
            'videos' => false,
            'ordered_images' => false,
            'preferred_orientation' => '2:3',
        ],
        'capabilities' => [
            'publish' => true,
            'schedule' => false,
            'edit' => false,
            'delete' => false,
            'analytics' => true,
            'inbox' => false,
            'pricing' => false,
            'inventory' => false,
            'boards' => true,
            'product_links' => true,
            'account_discovery' => true,
            'status_reconciliation' => true,
        ],
        'approval_required' => true,
    ],
];
